### ISSUE TITLE
Error when installing vulkan-utils in Ubuntu 22

### ISSUE THREAD

**Issue by olayasturias** [open-airlab/UNav-Sim#1]
+ sudo apt-get -y install --no-install-recommends lsb-release rsync software-properties-common wget libvulkan1 vulkan-utils
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package vulkan-utils

**Comment by abdelhakim96** [comment]
This issue has been solved in this branch: 

https://github.com/open-airlab/UNav-Sim/tree/ubuntu22
