### ISSUE TITLE
Issue with setup.sh

### ISSUE THREAD

**Issue by SixPathsOfSpain** [open-airlab/UNav-Sim#4]
## Bug report 

- AirSim Version/#commit:
- UE/Unity version: Unreal Engine 5
- autopilot version: N/A
- OS Version: Windows 10

### What's the issue you encountered?

Followed the attached steps for installation of unavsim but build.sh continually throws errors relating to rpclib 2.3.0. When trying to install this rpclib version, am unable to find this specific rpclib version. Continuing to get errors even though I have the latest rpclib version.

![image](https://github.com/open-airlab/UNav-Sim/assets/71959509/ffae753d-d68d-41fe-baf6-391471715412)

### How can the issue be reproduced?

1.  Followed the installation instructions provided by the unavsim team, up until the unavsim setup part.

### Include full error message in text form
```
echo 'ERROR: new version of AirSim requires newer rpclib.'
ERROR: new version of AirSim requires newer rpclib.

```

**What's better than filing an issue? Filing a pull request :).**

**Comment by abdelhakim96** [comment]
Hi,

For windows try running ` build.cmd` instead. I would also remove the build folder first.
