### ISSUE TITLE
Is there a sample project?

### ISSUE THREAD

**Issue by freezeLUO** [open-airlab/UNav-Sim#5]
### Smaller Details: 

I don’t know how to set up an underwater environment with this simulator. After I built a project, i can’t control the rov, which is suspended in mid air.

**Comment by abdelhakim96** [comment]
Hi, We are still working on the environments and we hope we can make them available soon.

For the ROV control, you can control individual thrusters using the Airsim API we have created. Here is some examples for an MPC controller you can use: 

https://github.com/abdelhakim96/UNav-Sim_ros

**Comment by zj-bohr** [comment]
.When I opened the items under the blocks folder, I didn't know how to import the underwater map. Looking forward to your reply.

**Comment by abdelhakim96** [comment]
As I mentioned, we haven't added the maps that we have used in the paper yet. For now, you can modify the blocks environments by adding the assets yourself.

**Comment by zj-bohr** [comment]
> 正如我所提到的，我们还没有添加我们在论文中使用的地图。现在，您可以通过自己添加资产来修改块环境。

ok.thanks.

**Comment by taeseongkr** [comment]
@abdelhakim96 Hi, could you please guide me how to import water map in this project? When I worked with drone AirSim, I download map from UE Fab (the market). Can I apply the same way to this project? Or do you have any sources which I can download from the market?
