### ISSUE TITLE
Motor Control

### ISSUE THREAD

**Issue by freezeLUO** [open-airlab/UNav-Sim#6]
### What's your question?

When controlling the motion of the ROV  using API(moveByMotorPWMsAsync) to manipulate the PWM of the motors, how should I reverse the motors to control the descent of the ROV?

**Comment by abdelhakim96** [comment]
Here is an example: 

```
vector<float> control_input{ -0.1f, -0.1f, -0.1f, -0.1f, 0.0, 0.0, 0.0, 0.0 };
        while (true) {
            client.moveByMotorPWMsAsync( control_input, duration);
        }
```
The first four entries in the control_input vector control the four vertical thrusters in the bluerov2 model. You just need to reverse the sign.

**Comment by abdelhakim96** [comment]
do you have the most recent version? There has been slight modification sometime ago that fixed this issue. Try to pull the latest version and rebuild.

 Check that the file here: `AirLib/include/vehicles/rov/RotorActuator.hpp`  have this line of code correct:           `control_signal_filter_.setInput(Utils::clip(control_signal, -1.0f, 1.0f)); `

**Comment by freezeLUO** [comment]
this line of code is correct in my RotorActuator.hpp

**Comment by abdelhakim96** [comment]
Hmmm, maybe you are using an old build? can you try clean and rebuilding? If it doesn't work, maybe its because its reading the file from the multirotor of airsim, so try to change the same line of code in this file instead: 
`AirLib\include\vehicles\multirotor\RotorActuator.hpp`

**Comment by freezeLUO** [comment]
OK，I will have a try...

**Comment by freezeLUO** [comment]
Hello, I have rebuild this project. When I run HelloROV with x64, I meet a problem (LNK1104 cannot open file “xxxxx\UNav-Sim\AirLib\lib\Win32\Debug\AirLib.lib”)，I find that this file(AirLib.lib) is not generated in this directory, insteadly, there is a AirLib.lib in generated x64\Debug\.

**Comment by abdelhakim96** [comment]
I hope the first issue is resolved.

Yes the example was not finished yet and the build system was not implemented. Please pull the latest version of UNavSim.

I have updated it. Its a simple P-Controller for the Bluerov. Feel free to try it out.

**Comment by abdelhakim96** [comment]
Thanks for letting us know! Glad it's sorted.
